@entryPoint = http://localhost:4100/api/v1

@accessToken = Authorization: Bearer 

@refreshToken = Authorization: Bearer 


#& -----------------------------------------------
#~ ------------------------------------------ USER
#& -----------------------------------------------

#~ ------------------------ doSignUp
###
POST {{entryPoint}}/signup
Content-Type: application/json

{
    "first_name": "Yumedo",
    "last_name": "Yumedo",
    "email": "yumedo@survivor.com",
    "password": "N6y$Ozddzt=1aa",
    "passwordConfirm": "N6y$Ozddzt=1aa"
}

#~ ------------------------ doSignIn
###
POST {{entryPoint}}/signin
Content-Type: application/json

{
  "email": "yumedo@survivor.com",
  "password": "N6y$Ozddzt=1aa"
}

#~ ------------------------ doSignOut
###
GET {{entryPoint}}/signout
Content-Type: application/json
{{refreshToken}}


#^ ------------------------ fetchAllUsers
###
GET {{entryPoint}}/users
Content-Type: application/json


#^ ------------------------ fetchOneUser
###
GET {{entryPoint}}/users/5
Content-Type: application/json
{{accessToken}}


#^ ------------------------ updateUser
###
PATCH {{entryPoint}}/users/11
Content-Type: application/json
{{accessToken}}

{
    "username": "Yumedo",
}


#^ ------------------------ deleteUser
###
DELETE {{entryPoint}}/users/13
Content-Type: application/json
{{accessToken}}

#& -----------------------------------------------
#~ --------------------------------------- ARTICLE
#& -----------------------------------------------

#^ ------------------------ createArticle
###
POST {{entryPoint}}/articles
Content-Type: application/json

{
    "title": "Super article !",
    "abstract": "Description de mon article",
    "content": "Ceci est mon article",
    "user_id": 1
}

#^ ------------------------ fetchAllArticles
###
GET {{entryPoint}}/articles
Content-Type: application/json

#^ ------------------------ fetchOneArticle
###
GET {{entryPoint}}/articles/1
Content-Type: application/json

#^ ------------------------ updateArticle
###
PATCH {{entryPoint}}/articles/1
Content-Type: application/json

{
    "title": "Super article modifié !",
    "abstract": "Description de mon article modifié",
    "content": "Ceci est mon article modifié",
    "user_id": 1
}

#^ ------------------------ deleteArticle
###
DELETE {{entryPoint}}/articles/1
Content-Type: application/json

#& -----------------------------------------------
#~ --------------------------------------- PROJECT
#& -----------------------------------------------

#^ ------------------------ createProject
###
POST {{entryPoint}}/projects
Content-Type: application/json

{
    "title": "Super projet !",
    "abstract": "Description de mon projet",
    "content": "Ceci est mon projet",
    "picture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/940.jpg",
    "date": "10 Mars 2022",
    "user_id": 1,
    "link": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/940.jpg"
}

#^ ------------------------ fetchAllProjects
###
GET {{entryPoint}}/projects
Content-Type: application/json

#^ ------------------------ fetchOneProject
###
GET {{entryPoint}}/projects/1
Content-Type: application/json


#^ ------------------------ updateProject
###
PATCH {{entryPoint}}/projects/1
Content-Type: application/json

{
    "title": "Super projet modifié !",
    "abstract": "Description de mon projet modifié",
    "content": "Ceci est mon projet modifié",
    "picture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/940.jpg",
    "date": "10 Mars 2022",
    "user_id": 1,
    "link": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/940.jpg"
}

#^ ------------------------ deleteProject
###
DELETE {{entryPoint}}/projects/1
Content-Type: application/json

#^ ------------------------ fetchAllProjectsWithCategories
###
GET {{entryPoint}}/projects/categories
Content-Type: application/json

#& -----------------------------------------------
#~ ------------------------------------- GB-TICKET
#& -----------------------------------------------

#^ ------------------------ createGoldenBookTicket
###
POST {{entryPoint}}/gb-tickets
Content-Type: application/json

{
  "content" : "test"
}

#^ ------------------------ fetchAllGoldenBookTickets
###
GET {{entryPoint}}/gb-tickets
Content-Type: application/json

#^ ------------------------ updateGoldenBookTicket
###
UPDATE {{entryPoint}}/gb-tickets/1
Content-Type: application/json

{
  "content" : "Update ticket"
}

#^ ------------------------ deleteGoldenBookTicket
###
DELETE {{entryPoint}}/gb-tickets/1
Content-Type: application/json



#& -----------------------------------------------
#~ -------------------------------------- CATEGORY
#& -----------------------------------------------

#^ ------------------------ createCategory
###
POST {{entryPoint}}/categories
Content-Type: application/json

{
  "name" : "test",
  "logo" : "svg",
  "color": "#000"
}

#^ ------------------------ fetchAllCategories
###
GET {{entryPoint}}/categories
Content-Type: application/json

#^ ------------------------ updateCategory
###
PATCH {{entryPoint}}/categories/1
Content-Type: application/json

{
  "name" : "test",
  "logo" : "svg",
  "color": "#000"
}

#^ ------------------------ deleteCategory
###
DELETE {{entryPoint}}/categories/1
Content-Type: application/json