@entryPoint = http://localhost:4100/api/v1

@accessToken = Authorization: Bearer 

@refreshToken = Authorization: Bearer 


#& -----------------------------------------------
#~ ------------------------------------------ USER
#& -----------------------------------------------

#~ ------------------------ doSignUp
###
POST {{entryPoint}}/signup
Content-Type: application/json

{
    "username": "Yumedo",
    "email": "yumedo9@survivor.com",
    "password": "N6y$Ozddzt=1aa",
    "passwordConfirm": "N6y$Ozddzt=1aa"
}

#~ ------------------------ doSignIn
###
POST {{entryPoint}}/signin
Content-Type: application/json

{
  "email": "yumedo@survivor.com",
  "password": "N6y$Ozddzt=1aa"
}

#~ ------------------------ doSignOut
###
GET {{entryPoint}}/signout
Content-Type: application/json
{{refreshToken}}


#^ ------------------------ fetchAllUsers
###
GET {{entryPoint}}/users
Content-Type: application/json


#^ ------------------------ fetchOneUser
###
GET {{entryPoint}}/users/5
Content-Type: application/json
{{accessToken}}


#^ ------------------------ updateUser
###
PATCH {{entryPoint}}/users/11
Content-Type: application/json
{{accessToken}}

{
    "username": "Yumedo",
}


#^ ------------------------ deleteUser
###
DELETE {{entryPoint}}/users/13
Content-Type: application/json
{{accessToken}}

#& -----------------------------------------------
#~ --------------------------------------- ARTICLE
#& -----------------------------------------------

#^ ------------------------ createArticle

#^ ------------------------ fetchOneArticle

#^ ------------------------ updateArticle

#^ ------------------------ deleteArticle

#& -----------------------------------------------
#~ --------------------------------------- PROJECT
#& -----------------------------------------------

#^ ------------------------ createProject

#^ ------------------------ fetchAllProjects

#^ ------------------------ fetchOneProject

#^ ------------------------ updateProject

#^ ------------------------ deleteProject

#& -----------------------------------------------
#~ ------------------------------------- GB-TICKET
#& -----------------------------------------------

#^ ------------------------ createGoldenBookTicket
###
POST {{entryPoint}}/gb-tickets
Content-Type: application/json

{
  "content" : "test",
  "created_at" : "svg"
}

#^ ------------------------ fetchAllGoldenBookTickets
###
GET {{entryPoint}}/gb-tickets
Content-Type: application/json

#^ ------------------------ updateGoldenBookTicket
###
UPDATE {{entryPoint}}/gb-tickets/1
Content-Type: application/json

{

}

#^ ------------------------ deleteGoldenBookTicket
###
DELETE {{entryPoint}}/gb-tickets/1
Content-Type: application/json

#& -----------------------------------------------
#~ -------------------------------------- CATEGORY
#& -----------------------------------------------

#^ ------------------------ createCategory
###
POST {{entryPoint}}/categories
Content-Type: application/json

{
  "name" : "test",
  "logo" : "svg",
  "color": "#000"
}

#^ ------------------------ fetchAllCategories
###
GET {{entryPoint}}/categories
Content-Type: application/json

#^ ------------------------ updateCategory
###
PATCH {{entryPoint}}/categories/1
Content-Type: application/json

{
  "name" : "test",
  "logo" : "svg",
  "color": "#000"
}

#^ ------------------------ deleteCategory
###
DELETE {{entryPoint}}/categories/1
Content-Type: application/json